# serverless.yml
# 详细配置文档: https://github.com/serverless-components/tencent-website/blob/master/docs/configure.md

component: website # (必填) 引用 component 的名称, 当前用到的是 tencent-website 组件
name: home # (必填) 该 website 组件创建的实例名称

app: home # (可选) 该 website 应用名称
stage: dev # (可选) 用于区分环境信息, 默认值是 dev

inputs:
  src:
    src: ./dist # upload static files
    index: index.html
    # dist: ./dist
    # hook: npm run build
    # websitePath: ./
  region: ap-beijing
  bucketName: home-bucket
  protocol: https
  replace: true
  autoRefresh: true
  autoSetupAcl: false